// export const GET_USERS = 'GET_USERS';
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const ADD_USER_REQUEST = 'ADD_USERS_REQUEST'
export const ADD_USER_SUCCESS = 'ADD_USERS_SUCCESS'
export const ADD_USER_FAILED = 'ADD_USERS_FAILED'

export const GET_SINGLE_USER = 'GET_SINGLE_USER'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_FAILED = 'GET_SINGLE_USER_FAILED'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED'

export const MODAL_STATUS = 'MODAL_STATUS'